Repository lutraconsulting/MDAL, pull requests merged in 2019-12, with the labels that each got.

#181 split linux jobs to 4
  .travis.yml
  scripts/ci/linux/build.bash
  scripts/ci/linux/install.bash
Labels: travis

#184 prepare unit test infrastructure
  CMakeLists.txt
  mdal/CMakeLists.txt
  mdal/frmts/mdal_sww.cpp
  mdal/frmts/mdal_ugrid.cpp
  mdal/frmts/mdal_xdmf.cpp
  mdal/mdal_utils.hpp
  tests/CMakeLists.txt
  tests/unittests/mdal_unittests.cpp
  tests/unittests/test_mdal_utils.cpp
Labels: travis

#179 time handling
  mdal/CMakeLists.txt
  mdal/api/mdal.h
  mdal/frmts/mdal_3di.cpp
  mdal/frmts/mdal_ascii_dat.cpp
  mdal/frmts/mdal_ascii_dat.hpp
  mdal/frmts/mdal_binary_dat.cpp
  mdal/frmts/mdal_binary_dat.hpp
  mdal/frmts/mdal_cf.cpp
  mdal/frmts/mdal_cf.hpp
  mdal/frmts/mdal_driver.cpp
  mdal/frmts/mdal_driver.hpp
  mdal/frmts/mdal_flo2d.cpp
  mdal/frmts/mdal_gdal.cpp
  mdal/frmts/mdal_gdal.hpp
  mdal/frmts/mdal_gdal_grib.cpp
  mdal/frmts/mdal_gdal_grib.hpp
  mdal/frmts/mdal_gdal_netcdf.cpp
  mdal/frmts/mdal_gdal_netcdf.hpp
  mdal/frmts/mdal_hec2d.cpp
  mdal/frmts/mdal_hec2d.hpp
  mdal/frmts/mdal_selafin.cpp
  mdal/frmts/mdal_selafin.hpp
  mdal/frmts/mdal_sww.cpp
  mdal/frmts/mdal_xdmf.cpp
  mdal/frmts/mdal_xdmf.hpp
  mdal/frmts/mdal_xmdf.cpp
  mdal/frmts/mdal_xmdf.hpp
  mdal/mdal.cpp
  mdal/mdal_data_model.cpp
  mdal/mdal_data_model.hpp
  mdal/mdal_datetime.cpp
  mdal/mdal_datetime.hpp
  mdal/mdal_utils.cpp
  mdal/mdal_utils.hpp
  tests/CMakeLists.txt
  tests/data/datetime/julianDay.txt
  tests/mdal_testutils.cpp
  tests/mdal_testutils.hpp
  tests/test_3di.cpp
  tests/test_ascii_dat.cpp
  tests/test_binary_dat.cpp
  tests/test_flo2d.cpp
  tests/test_gdal_grib.cpp
  tests/test_gdal_netcdf.cpp
  tests/test_hec2d.cpp
  tests/test_selafin.cpp
  tests/test_sww.cpp
  tests/test_tuflowfv.cpp
  tests/test_ugrid.cpp
  tests/test_xdmf.cpp
  tests/test_xmdf.cpp
  tests/unittests/test_mdal_datetime.cpp
  tests/unittests/test_mdal_utils.cpp
Labels: enhancement

#189 fix #187 bug when reading binary dat files
  mdal/frmts/mdal_2dm.cpp
  mdal/frmts/mdal_ascii_dat.cpp
  mdal/mdal_utils.cpp
  mdal/mdal_utils.hpp
Labels: needs backport, regression
